language: java

matrix:
  include:
  - name: "Java 9"
      jdk: oraclejdk9
      env: JAVA_VERSION=9
  - name: "Java 10"
      jdk: oraclejdk10
      env: JAVA_VERSION=10
  - name: "Java 11"
      jdk: oraclejdk11
      env: JAVA_VERSION=11
  script: mvn clean verify -djava.version=$JAVA_VERSION
  
addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
