language: java

jdk:
  - openjdk13

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

script:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
