language: java

jdk:
  - openjdk13

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

# the dependency benjaminkomen/jwiki recides in GitHub Packages, for which you need credentials to download.
# They are set here, with the GITHUB_TOKEN in Travis.
install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

script:
  - ./mvnw clean verify sonar:sonar -Pcoverage
