language: java

jdk:
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

env:
  - JAVA_VERSION=9
  - JAVA_VERSION=10
  - JAVA_VERSION=11

addons:
  sonarcloud:
    organization: "benjaminkomen-github"

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Djava.version=$JAVA_VERSION
